spring.security.user.name=admin
spring.security.user.password=admin

spring.application.name=brand-analytics
spring.profiles.active=prod

# Amazon API - constants
amazon.baseUrl=https://sellingpartnerapi-eu.amazon.com/
amazon.authUrl=https://api.amazon.com/auth/o2/token
amazon.ordersEndpoint=/orders/v0/orders
amazon.reportsEndpoint=/reports/2021-06-30/reports
amazon.reportDocumentEndpoint=/reports/2021-06-30/documents
amazon.marketplaceId=A21TJRUUN4KGV

amazon.rateLimits.getOrders.ratePerSecond=0.0167
amazon.rateLimits.getOrders.burstRequests=20
amazon.rateLimits.getOrder.ratePerSecond=0.5
amazon.rateLimits.getOrder.burstRequests=30

# Spring JPA
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Inject secrets from env
amazon.clientId=${AMAZON_CLIENTID:dummy}
amazon.clientSecret=${AMAZON_CLIENTSECRET:dummy}
amazon.refreshToken=${AMAZON_REFRESHTOKEN:dummy}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/brand_analytics}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:brand-admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}